# common service/environment definitions for docker-compose configurations
opentpod_djangoapp:
    image: opentpod:stable
    volumes:
        - opentpod-data-var:/root/openTPOD/var
    environment:
        - DJANGO_ALLOWED_HOSTS
        - DJANGO_SECRET_KEY
        - DJANGO_DEBUG=false
        - PYTHONDONTWRITEBYTECODE=1
        - REDIS_URL="redis://:${OPENTPOD_REDIS_PASSWORD}@opentpod-redis:6379/"
        - REDIS_CACHE_URL="redis://:${OPENTPOD_REDIS_PASSWORD}@$opentpod-redis:6379/1"
        - DATABASE_URL="postgres://root:${OPENTPOD_DB_PASSWORD}@$opentpod-db:5432/${OPENTPOD_DB}"
    depends_on:
        - opentpod-db
        - opentpod-redis
