# docker-compose.override.yml for development. Only brings up minimal set
# of containers, postgresql, redis, opentpod and one opentpod-worker that
# handles all jobs.
#
#     docker-compose up -d
#
version: "3.2"
services:
    opentpod:
        build: .
        image: opentpod:latest
        command: [ "./run-development.sh" ]
        volumes:
            # mount local source into container
            - ./config:/root/openTPOD/config:ro
            - ./cvat:/root/openTPOD/cvat:ro
            - ./datumaro:/root/openTPOD/datumaro:ro
            - ./frontend/src:/root/openTPOD/frontend/src:ro
            - ./manage.py:/root/openTPOD/manage.py:ro
            - ./opentpod:/root/openTPOD/opentpod:ro
        ports:
            - 127.0.0.1:20000:8000
        environment:
            - DJANGO_DEBUG=true
    opentpod-worker: &opentpod-worker
        build: .
        image: opentpod:latest
        command: [ "./run-worker.sh", "default" ]
        volumes:
            - ./config:/root/openTPOD/config:ro
            - ./cvat:/root/openTPOD/cvat:ro
            - ./datumaro:/root/openTPOD/datumaro:ro
            - ./manage.py:/root/openTPOD/manage.py:ro
            - ./opentpod:/root/openTPOD/opentpod:ro
        environment:
            - DJANGO_DEBUG=true
            - NVIDIA_VISIBLE_DEVICES=all # needed for cuda devices to be visible
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    opentpod-trainer:
        <<: *opentpod-worker
        command: [ "./run-worker.sh", "low" ]
