# should be used together with docker-compose for production development
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: "3.2"
volumes:
    opentpod-data-var:
    opentpod-db-data:
    opentpod-redis-data:
    opentpod-www-static:
services:
    opentpod-db:
        image: postgres:12.0-alpine
        container_name: opentpod-db
        restart: always
        volumes:
            - opentpod-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: ${OPENTPOD_DB}
            POSTGRES_PASSWORD: ${OPENTPOD_DB_PASSWORD}
    opentpod-db-viewer:
        image: adminer
        container_name: opentpod-db-viewer
        restart: always
        depends_on:
            - opentpod-db
        ports:
            - 127.0.0.1:${OPENTPOD_DB_VIEWER_PORT}:8080
        depends_on:
            - opentpod-db
    opentpod-redis:
        container_name: opentpod-redis
        image: redis:4.0.5-alpine
        command: --appendonly yes --requirepass "$$OPENTPOD_REDIS_PASSWORD"
        volumes:
            - opentpod-redis-data:/data
    opentpod-nginx:
        image: nginx:latest
        container_name: opentpod-nginx
        ports:
            - 0.0.0.0:20000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/opentpod.nginx.conf:/etc/nginx/opentpod.nginx.conf:ro
            - opentpod-www-static:/root/openTPOD/www:ro
            - opentpod-data-var:/root/openTPOD/var
        depends_on:
            - opentpod
    opentpod:
        image: opentpod:stable
        container_name: opentpod
        command: [ "./run-frontend.sh" ]
        volumes:
            - opentpod-www-static:/root/openTPOD/www
            - opentpod-data-var:/root/openTPOD/var
        ports:
            - 127.0.0.1:20001:8000
        environment:
            - PYTHONDONTWRITEBYTECODE
            - DJANGO_DEBUG
            - DJANGO_SECRET_KEY
            - DJANGO_ALLOWED_HOSTS
            - REDIS_URL
            - REDIS_CACHE_URL
            - DATABASE_URL
        depends_on:
            - opentpod-db
            - opentpod-redis
    opentpod-worker:
        image: opentpod:stable
        command: [ "./run-worker.sh", "default" ]
        volumes:
            - opentpod-data-var:/root/openTPOD/var
        environment:
            - PYTHONDONTWRITEBYTECODE
            - DJANGO_DEBUG
            - DJANGO_SECRET_KEY
            - REDIS_URL
            - DATABASE_URL
        depends_on:
            - opentpod
    opentpod-tensorboard:
        extends: opentpod-worker
        command: [ "./run-worker.sh", "tensorboard" ]
        environment:
            - NVIDIA_VISIBLE_DEVICES=all # needed for cuda devices to be visible
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    opentpod-trainer:
        extends: opentpod-worker
        command: [ "./run-worker.sh", "low" ]
        environment:
            - NVIDIA_VISIBLE_DEVICES=all # needed for cuda devices to be visible
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
