# Generated by Django 2.2.3 on 2019-11-14 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0021_auto_20190826_1827'),
        ('object_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(to='engine.Video')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
