# Generated by Django 2.2.3 on 2019-11-14 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0002_trainset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainset',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
