# Generated by Django 2.2.3 on 2019-11-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0003_auto_20191114_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detector',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='detector',
            name='dnn_type',
            field=models.CharField(choices=[('PH', 'placeholder')], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detector',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_detector.Detector'),
        ),
        migrations.AddField(
            model_name='detector',
            name='trainset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_detector.TrainSet'),
        ),
    ]
