# Generated by Django 2.2.3 on 2019-11-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0004_auto_20191115_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_classes', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('num_steps', models.PositiveIntegerField(default=10000)),
                ('fine_tune_checkpoint', models.CharField(max_length=2000)),
                ('detector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='object_detector.Detector')),
            ],
        ),
    ]
