# Generated by Django 2.2.3 on 2019-11-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0005_trainconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='trainset',
            new_name='train_set',
        ),
        migrations.AddField(
            model_name='detector',
            name='train_config',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detector',
            name='dnn_type',
            field=models.CharField(choices=[('tensorflow_faster_rcnn_resnet101', 'Tensorflow Faster-RCNN ResNet 101')], max_length=32),
        ),
        migrations.DeleteModel(
            name='TrainConfig',
        ),
    ]
