# Generated by Django 2.2.3 on 2019-11-23 22:11

from django.db import migrations, models
import opentpod.object_detector.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0007_auto_20191122_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'CREATED'), ('training', 'TRAINING'), ('trained', 'TRAINED'), ('error', 'ERROR')], default=opentpod.object_detector.models.Status('created'), max_length=32, null=True),
        ),
    ]
