# Generated by Django 2.2.3 on 2019-11-24 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0008_auto_20191123_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
