# Generated by Django 2.2.10 on 2020-06-26 21:00

import django.core.files.storage
from django.db import migrations, models
import opentpod.object_detector.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0010_auto_20200217_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/root/openTPOD/var'), upload_to=opentpod.object_detector.models.upload_file_handler)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
