# Generated by Django 2.2.10 on 2020-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0011_detectormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectormodel',
            name='feature_extractor_type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
