# Generated by Django 2.2.10 on 2020-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0013_auto_20200629_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(upload_to='TrainModel/<built-in function id>'),
        ),
    ]
