# Generated by Django 2.2.10 on 2020-06-29 16:02

from django.db import migrations, models
import opentpod.object_detector.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0014_auto_20200629_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(upload_to=opentpod.object_detector.models.upload_file_handler),
        ),
    ]
