# Generated by Django 2.2.10 on 2020-06-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0015_auto_20200629_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectormodel',
            options={'ordering': ['id']},
        ),
    ]
