# Generated by Django 2.2.10 on 2020-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0021_remove_detectormodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(upload_to='TrainModel/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
