# Generated by Django 2.2.10 on 2020-07-16 17:38

from django.db import migrations, models
import opentpod.object_detector.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0022_auto_20200716_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(upload_to=opentpod.object_detector.models.upload_file_handler),
        ),
    ]
