# Generated by Django 2.2.10 on 2020-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0024_modelpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='dnn_type',
            field=models.CharField(max_length=32),
        ),
    ]
