# Generated by Django 2.2.10 on 2020-07-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0026_auto_20200720_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='dnn_type',
            field=models.CharField(choices=[('tensorflow_faster_rcnn_resnet101', 'Tensorflow Faster-RCNN ResNet 101'), ('tensorflow_faster_rcnn_resnet50', 'Tensorflow Faster-RCNN ResNet 50'), ('tensorflow_ssd_mobilenet_v2', 'Tensorflow SSD MobileNet V2'), ('Self-trained', 'Self-trained'), ('GoogleAutoML', 'GoogleAutoML')], max_length=32),
        ),
    ]
